# Generated by Django 4.2.30 on 2026-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='用户ID')),
                ('course_id', models.CharField(db_index=True, max_length=64, verbose_name='关联课程ID')),
                ('doc_id', models.CharField(max_length=256, unique=True, verbose_name='文档唯一ID')),
                ('file_name', models.CharField(max_length=256, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=512, verbose_name='文件路径')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('txt', 'TXT'), ('md', 'Markdown')], max_length=16, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('chunks_count', models.IntegerField(default=0, verbose_name='分块数量')),
                ('course_name', models.CharField(blank=True, max_length=128, verbose_name='关联课程名')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('vectorized', '已向量化'), ('failed', '失败')], default='uploaded', max_length=16, verbose_name='状态')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'db_table': 'user_knowledge_file',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user_id', 'course_id'], name='user_knowle_user_id_389c86_idx')],
            },
        ),
    ]
