# Generated by Django 4.2.30 on 2026-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='用户ID')),
                ('course_id', models.CharField(max_length=64, unique=True, verbose_name='课程编号')),
                ('course_name', models.CharField(max_length=128, verbose_name='课程名称')),
                ('teacher', models.CharField(default='待定', max_length=64, verbose_name='授课教师')),
                ('weekday', models.SmallIntegerField(verbose_name='星期(0=周一,6=周日)')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('location', models.CharField(default='待定', max_length=128, verbose_name='上课地点')),
                ('week_range', models.CharField(default='1-16', max_length=32, verbose_name='周次范围')),
                ('semester', models.CharField(default='2025-2026-2', max_length=32, verbose_name='学期')),
                ('status', models.CharField(choices=[('active', '有效'), ('cancelled', '已取消'), ('finished', '已结课')], default='active', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'user_schedule',
                'ordering': ['weekday', 'start_time'],
                'indexes': [models.Index(fields=['user_id', 'semester'], name='user_schedu_user_id_c30061_idx'), models.Index(fields=['user_id', 'weekday'], name='user_schedu_user_id_b81a98_idx')],
            },
        ),
    ]
