# Generated by Django 4.2.30 on 2026-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='用户ID')),
                ('session_id', models.CharField(db_index=True, max_length=128, verbose_name='会话ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=16, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('tool_calls', models.JSONField(default=list, verbose_name='工具调用记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'agent_chat_history',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user_id', 'session_id'], name='agent_chat__user_id_969e40_idx')],
            },
        ),
    ]
