# Generated by Django 4.2.30 on 2026-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='用户ID')),
                ('plan_id', models.CharField(db_index=True, max_length=64, verbose_name='计划ID')),
                ('task_id', models.CharField(max_length=64, unique=True, verbose_name='任务ID')),
                ('task_name', models.CharField(max_length=256, verbose_name='任务名称')),
                ('subject', models.CharField(max_length=64, verbose_name='科目')),
                ('date', models.DateField(verbose_name='日期')),
                ('weekday', models.SmallIntegerField(default=0, verbose_name='星期(0=周一)')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='时长(分钟)')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('dependencies', models.JSONField(default=list, verbose_name='依赖任务ID列表')),
                ('plan_config', models.JSONField(default=dict, verbose_name='计划配置')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'user_task',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['user_id', 'plan_id'], name='user_task_user_id_0b2305_idx'), models.Index(fields=['user_id', 'date'], name='user_task_user_id_1686d4_idx')],
            },
        ),
    ]
